Repository codeit-frontend-part3-team3/The-julge, pull requests merged in 2024-12, with the labels that each got.

#7 전역 폰트 셋팅 추가 작업
  public/file.svg
  public/fonts/SpoqaHanSansNeo-Bold.woff2
  public/fonts/SpoqaHanSansNeo-Medium.woff2
  public/fonts/SpoqaHanSansNeo-Regular.woff2
  public/globe.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/app/globals.css
  tailwind.config.ts
Labels: 세팅, 스타일

#28 Feature/#5 Input 공통 컴포넌트 작업
  package-lock.json
  package.json
  public/image/dropdown-triangle.svg
  src/app/_components/Dropdown.tsx
  src/app/_components/Input.tsx
  src/app/_components/footer.tsx
  src/app/globals.css
  tailwind.config.ts
Labels: 컴포넌트

#35 이슈 템플릿 셋팅
  .github/ISSUE_TEMPLATE/request.md
  .github/ISSUE_TEMPLATE/task_plan.md
  .prettierrc.js
Labels: 문서, 세팅

#13 footer 컴포넌트 반응형 코드 수정
  src/app/_components/footer.tsx
Labels: 스타일, 업데이트

#37 Feature/#10 header공통컴포넌트작업
  package-lock.json
  package.json
  public/image/logo.svg
  public/image/notification-active.svg
  public/image/notification-inactive.svg
  public/image/search.svg
  src/app/_components/header.tsx
Labels: 컴포넌트, 패키지

#39 Feature/#8 button공통컴포넌트작업
  src/app/_api/api.ts
  src/app/_components/Button.tsx
  src/app/_hooks/useHook.ts
Labels: 컴포넌트

#40 Feature/#38 상세필터공통컴포넌트작업
  public/image/closeBtn.svg
  src/app/_components/DetailFilter.tsx
  src/app/_components/Input.tsx
  src/app/_components/footer.tsx
  src/app/_components/header.tsx
  src/app/_constants/Location.ts
  src/app/globals.css
Labels: 컴포넌트

#45 Feature/#44 커스텀훅분리
  src/app/_components/Logo.tsx
  src/app/_components/footer.tsx
  src/app/_components/header.tsx
  src/app/_hooks/useLogrinStatus.ts
  src/app/_hooks/useNotifications.ts
  src/app/_hooks/useWindowWidth.ts
Labels: 리팩토링, 커스텀훅, 업데이트

#42 Feature/#32 modal공통컴포넌트작업
  public/image/modal-alert.svg
  public/image/modal-question.svg
  src/app/_components/Button.tsx
  src/app/_components/Modal.tsx
  src/app/_config/modalConfig.ts
  src/app/_hooks/useModal.ts
  tailwind.config.ts
Labels: 컴포넌트, 세팅, 커스텀훅

#50 Refactor: Input 컴포넌트에 InputHTMLAttributes 확장 적용
  src/app/_components/Input.tsx
Labels: 리팩토링, 업데이트

#48 Feature/#41 뱃지컴포넌트작업
  public/image/arrow-up-bold.svg
  src/app/_components/Badge.tsx
  src/app/_components/Button.tsx
  src/app/page.tsx
Labels: 컴포넌트

#53 버튼 사이즈 추가작업 xxs 추가
  src/app/_components/Button.tsx
  src/app/page.tsx
Labels: 업데이트

#54 Feature/#47 프로필정보등록공통컴포넌트
  src/app/_components/PostProfile.tsx
  src/app/globals.css
Labels: 컴포넌트

#51 헤더 알림 공통 컴포넌트
  src/app/_components/NotificationModal/NotificationModal.tsx
  src/app/_components/NotificationModal/types.ts
Labels: 컴포넌트

#59 토스트 공통 컴포넌트
  src/app/_components/Toast/Toast.tsx
  src/app/_components/Toast/ToastContainer.tsx
Labels: 컴포넌트

#58 Feature/#57 공통컴포넌트타입리팩토링
  src/app/_components/Dropdown.tsx
  src/app/_components/Modal.tsx
Labels: 리팩토링, 업데이트

#65 Feature/#61 상세필터리렌더링방지
  src/app/_components/DetailFilter.tsx
  src/app/_components/header.tsx
Labels: 업데이트

#55 Feature/#36 테이블공통컴포넌트
  src/app/_components/Table.tsx
  src/app/_config/tableConfig.tsx
  src/app/page.tsx
  tailwind.config.ts
Labels: 컴포넌트, 리팩토링

#72 Feature/#64 가게정보등록페이지구현
  src/app/_components/DetailFilter.tsx
  src/app/_components/Dropdown.tsx
  src/app/_constants/constants.ts
  src/app/store/post/page.tsx
Labels: 페이지

#69 Feature/#68 헤더알림모달연결
  src/app/_components/NotificationModal/NotificationModal.tsx
  src/app/_components/header.tsx
  src/app/_hooks/useLoginStatus.ts
  src/app/_hooks/useLogrinStatus.ts
Labels: 컴포넌트

#78 Feature/#75 input컴포넌트에use hook form구현
  package-lock.json
  package.json
  src/app/_components/Dropdown.tsx
  src/app/_components/ImageUploader.tsx
  src/app/_components/Input.tsx
  src/app/store/post/page.tsx
Labels: 패키지, 페이지, 신규기능

#74 헤더 알림 모달 리팩토링
  src/app/_components/NotificationModal/NotificationModal.tsx
Labels: 리팩토링

#79 Feat: 가게 정보 수정 페이지 구현
  src/app/_components/ImageUploader.tsx
  src/app/_context/AuthContext.tsx
  src/app/store/edit/page.tsx
Labels: 페이지, 스타일

#81 Feature/#70 내 프로필 등록 페이지 구현
  src/app/_components/Dropdown.tsx
  src/app/profile/page.tsx
  src/app/profile/post/page.tsx
Labels: API, 페이지

#82 각 페이지별 API 작업 / 이미지훅
  package-lock.json
  package.json
  src/app/_api/alarm_api.ts
  src/app/_api/announce_api.ts
  src/app/_api/auth_api.ts
  src/app/_api/imageURL_api.ts
  src/app/_api/owner_api.ts
  src/app/_api/worker_api.ts
  src/app/_components/Table.tsx
  src/app/_context/AuthContext.tsx
  src/app/_hooks/useCreateImgUrl.ts
  src/app/_hooks/useImageCompressor.ts
  src/app/_types/alarm.d.ts
  src/app/_types/announce.d.ts
  src/app/_types/auth.d.ts
  src/app/_types/owner.d.ts
  src/app/_types/worker.d.ts
Labels: API, 패키지, 신규기능, 커스텀훅

#87 Feat: 가게 공고 등록 페이지 구현
  src/app/announce/post/page.tsx
  src/app/store/edit/page.tsx
  src/app/store/post/page.tsx
Labels: 페이지, 스타일

#85 Feature/#83 내프로필등록페이지use hook form연결
  src/app/_components/Dropdown.tsx
  src/app/profile/post/page.tsx
  src/app/store/edit/page.tsx
  src/app/store/post/page.tsx
Labels: 페이지, 업데이트

#90 Feature/#88 이미지 업로드 로직 수정
  next.config.ts
  src/app/_api/globaltoken.ts
  src/app/_api/imageURL_api.ts
  src/app/_api/instance.ts
  src/app/_components/ImageUploader.tsx
  src/app/_context/AuthContext.tsx
  src/app/_hooks/useCreateImgUrl.ts
  src/app/_hooks/useImageCompressor.ts
  src/app/_types/auth.d.ts
  src/app/announce/post/page.tsx
  src/app/store/edit/page.tsx
  src/app/store/post/page.tsx
Labels: API, 버그

#92 회원가입 페이지
  public/image/icon-checked.svg
  public/image/icon-unchecked.svg
  src/app/_api/globaltoken.ts
  src/app/_api/instance.ts
  src/app/_components/Button.tsx
  src/app/_components/Logo.tsx
  src/app/_context/AuthContext.tsx
  src/app/_types/auth.d.ts
  src/app/signup/page.tsx
  tailwind.config.ts
Labels: 페이지, 신규기능

#93 Feature/#91 가게정보등록api구현및리팩토링
  src/app/_components/Dropdown.tsx
  src/app/_components/Input.tsx
  src/app/_components/Modal.tsx
  src/app/_hooks/useModal.ts
  src/app/store/post/page.tsx
Labels: API, 페이지, 리팩토링

#97 로그인 페이지 작업 완료
  src/app/_api/instance.ts
  src/app/login/page.tsx
  src/app/signup/page.tsx
Labels: 페이지, 신규기능

#96 Feature/#86 내프로필상세페이지구현
  public/image/location.svg
  public/image/phone.svg
  src/app/_components/Table.tsx
  src/app/profile/_components/ProfileCard.tsx
  src/app/profile/_type/type.tsx
  src/app/profile/page.tsx
Labels: 페이지

#98 Feat/Refactor: 가게 정보 수정 페이지 API 구현 및 코드 리팩토링
  src/app/login/page.tsx
  src/app/signup/page.tsx
  src/app/store/edit/[id]/page.tsx
  src/app/store/edit/page.tsx
Labels: API, 페이지, 리팩토링

#104 헤더 컴포넌트 AuthContext를 이용한 로그인 상태 확인
  src/app/_components/header.tsx
Labels: 업데이트

#102 Feature/#100 가게상세페이지구현
  src/app/store/detail/page.tsx
Labels: 페이지

#106 #60 카드공통컴포넌트
  next.config.ts
  public/image/arrow-up-bold-red.svg
  public/image/clock-icon-off.svg
  public/image/clock-icon.svg
  public/image/path11-off.svg
  public/image/path11.svg
  src/app/_components/Badge.tsx
  src/app/_components/PostCard/PostCard.tsx
  src/app/_components/PostCard/PostCardV.1.tsx
  src/app/_components/PostCard/PostCardV2.tsx
  src/app/page.tsx
Labels: 컴포넌트

#105 Feature/#99 공고등록api구현및리팩토링
  src/app/_api/imageURL_api.ts
  src/app/_components/ImageUploader.tsx
  src/app/announce/post/page.tsx
Labels: API, 페이지, 리팩토링

#111 Feat: 404 에러 페이지 구현
  public/image/error-icon.svg
  src/app/not-found.tsx
  src/app/store/detail/page.tsx
Labels: 페이지

#113 Feature/#109 가게상세페이지구현2
  src/app/_components/footer.tsx
  src/app/store/detail/page.tsx
Labels: 페이지

#116 Feature/#115 프로필페이지에유저데이터연결
  src/app/_components/PostProfile.tsx
  src/app/_components/header.tsx
  src/app/_config/tableConfig.tsx
  src/app/profile/_components/ProfileCard.tsx
  src/app/profile/page.tsx
  src/app/profile/post/[id]/page.tsx
Labels: API, 페이지, 업데이트

#119 import, footer,header 대소문자 수정
  src/app/_components/DetailFilter.tsx
  src/app/announce/post/page.tsx
  src/app/store/detail/page.tsx
Labels: 버그

#121 announce import header footer수정
  src/app/announce/post/page.tsx
Labels: 버그

#122 Feature/#117 내가게상세페이지구조수정
  src/app/_components/PostCard/PostCardV.1.tsx
  src/app/_components/PostProfile.tsx
  src/app/_components/header.tsx
  src/app/_types/auth.d.ts
  src/app/store/detail/page.tsx
  src/app/store/post/page.tsx
Labels: API, 페이지, 업데이트

#126 Feature/#125 header컴포넌트메뉴경로수정
  src/app/_components/header.tsx
Labels: 리팩토링, 업데이트

#133 Feature/#127 메인공고관련페이지작업
  src/app/_components/Badge.tsx
  src/app/_components/Button.tsx
  src/app/_components/DetailFilter.tsx
  src/app/_components/Pagination.tsx
  src/app/_components/PostCard/DetailPostCard.tsx
  src/app/_components/PostCard/PostCard.tsx
  src/app/_components/PostCard/PostCardV.1.tsx
  src/app/_context/AppContext.tsx
  src/app/_context/AuthContext.tsx
  src/app/_context/NoticeContext.tsx
  src/app/_hooks/useAlbaTimeFormat.ts
  src/app/_hooks/useCreateImgUrl.ts
  src/app/_hooks/useImageCompressor.ts
  src/app/_hooks/useMouseDrag.ts
  src/app/announce/_components/AllNotices.tsx
  src/app/announce/_components/UserNotice.tsx
  src/app/announce/detail/[id]/page.tsx
  src/app/announce/page.tsx
  src/app/globals.css
  src/app/page.tsx
Labels: 페이지, 긴급, 신규기능, 커스텀훅, 업데이트

#129 데이터 값이 있을 때 삽입되도록 수정
  src/app/profile/post/[id]/page.tsx
Labels: 페이지, 업데이트

#130 PostCard 디자인 수정, 타입 추가
  src/app/_components/PostCard/PostCard.tsx
  src/app/_components/PostCard/PostCardV.1.tsx
  src/app/_components/PostCard/PostCardV2.tsx
Labels: 스타일, 버그

#135 공고상세,주소필터작업
  src/app/_api/instance.ts
  src/app/_components/PostCard/DetailPostCard.tsx
  src/app/_constants/locationData.ts
  src/app/_context/NoticeContext.tsx
  src/app/_context/util/recentNotices.ts
  src/app/_hooks/useFilteredNotices.ts
  src/app/_hooks/useGeolocation.ts
  src/app/_types/announce.d.ts
  src/app/announce/_components/AllNotices.tsx
  src/app/announce/_components/UserNotice.tsx
  src/app/announce/detail/[id]/page.tsx
  src/app/page.tsx
Labels: 페이지, 신규기능, 커스텀훅

#139 postcard 버그수정
  src/app/_components/PostCard/PostCard.tsx
Labels: 긴급, 버그

#140 Feature/#136 헤더검색기능작업상세필터작업
  src/app/_components/DetailFilter/DetailFilter.tsx
  src/app/_components/DetailFilter/SelectAmount.tsx
  src/app/_components/DetailFilter/SelectLocation.tsx
  src/app/_components/DetailFilter/SelectStartData.tsx
  src/app/_components/Header/Header.tsx
  src/app/_components/Header/Menu.tsx
  src/app/_components/Header/Search.tsx
  src/app/_components/ImageUploader.tsx
  src/app/_components/PostCard/DetailPostCard.tsx
  src/app/_components/PostCard/PostCard.tsx
  src/app/_components/PostCard/PostCardV.1.tsx
  src/app/_components/header.tsx
  src/app/announce/_components/AllNotices.tsx
  src/app/announce/page.tsx
  src/app/announce/post/page.tsx
  src/app/page.tsx
  src/app/profile/page.tsx
  src/app/profile/post/[id]/page.tsx
  src/app/search/page.tsx
  src/app/store/detail/page.tsx
  src/app/store/edit/[id]/page.tsx
  src/app/store/post/page.tsx
Labels: 컴포넌트, 페이지, 리팩토링, 업데이트

#143 Feature/#141 프로필페이지리다이렉트현상수정
  src/app/_components/PostCard/PostCard.tsx
  src/app/profile/page.tsx
  src/app/profile/post/[id]/page.tsx
Labels: 페이지, 긴급

#146 Feature/#144 로딩컴포넌트구현
  src/app/_components/Footer.tsx
  src/app/_components/Loding.tsx
  src/app/announce/detail/[id]/page.tsx
  src/app/announce/post/page.tsx
  src/app/login/page.tsx
  src/app/profile/page.tsx
  src/app/profile/post/[id]/page.tsx
  src/app/search/page.tsx
  src/app/signup/page.tsx
  src/app/store/detail/page.tsx
  src/app/store/edit/[id]/page.tsx
  src/app/store/post/page.tsx
Labels: 컴포넌트, 리팩토링

#148 공고상세테이블부분사장님시점
  src/app/_components/Modal.tsx
  src/app/_components/PostCard/DetailPostCard.tsx
  src/app/_components/PostCard/PostCard.tsx
  src/app/_config/modalConfig.ts
  src/app/_config/tableConfig.tsx
  src/app/_context/AuthContext.tsx
  src/app/announce/detail/[id]/page.tsx
  src/app/announce/page.tsx
Labels: 긴급, 업데이트

#151 Feat: 공고 편집 페이지 구현
  src/app/announce/edit/page.tsx
Labels: 페이지, 긴급

#153 공고편집하기 경로작업
  src/app/_components/PostCard/DetailPostCard.tsx
Labels: 긴급, 업데이트

#149 PostCard를 DetailPostCard 컴포넌트로 수정
  src/app/_components/Header/Header.tsx
  src/app/store/detail/page.tsx
Labels: 페이지, 긴급, 리팩토링

#157 Fix: 공고 편집하기 시작 시간 데이터 형식 버그 수정
  src/app/announce/edit/page.tsx
Labels: 페이지, 긴급, 버그

#158 Feature/#155 검색페이지수정
  src/app/_components/PostCard/PostCard.tsx
  src/app/announce/detail/[id]/page.tsx
  src/app/search/page.tsx
  src/app/store/detail/page.tsx
Labels: 긴급, 리팩토링

#164 Feature/#154 버그이슈신청api
  package-lock.json
  package.json
  src/app/_components/PostCard/DetailPostCard.tsx
  src/app/_components/PostCard/PostCard.tsx
  src/app/_components/Table.tsx
  src/app/_config/tableConfig.tsx
  src/app/announce/detail/[id]/page.tsx
  tailwind.config.ts
Labels: 긴급, 신규기능, 버그, 업데이트

#162 알람 모달 수정
  package-lock.json
  package.json
  src/app/_components/Header/Header.tsx
  src/app/_components/NotificationModal/NotificationModal.tsx
  src/app/_components/NotificationModal/types.ts
Labels: API, 긴급

#167 내 가게 수정 페이지로 이동 성공
  src/app/_components/ImageUploader.tsx
  src/app/signup/page.tsx
  src/app/store/detail/page.tsx
  src/app/store/edit/[id]/page.tsx
Labels: 긴급, 업데이트

#170 각종 빌드에러 수정, 프리티어, 린트 삭제
  .eslintrc.js
  .github/ISSUE_TEMPLATE/request.md
  .github/ISSUE_TEMPLATE/task_plan.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/closed-jira-Issue.yml
  .github/workflows/create-jira-issue.yml
  .prettierrc.js
  package-lock.json
  package.json
  src/app/_api/alarm_api.ts
  src/app/_api/announce_api.ts
  src/app/_api/auth_api.ts
  src/app/_api/globaltoken.ts
  src/app/_api/imageURL_api.ts
  src/app/_api/instance.ts
  src/app/_api/owner_api.ts
  src/app/_api/worker_api.ts
  src/app/_components/ArrowButton.tsx
  src/app/_components/Badge.tsx
  src/app/_components/Button.tsx
  src/app/_components/NotificationModal/NotificationModal.tsx
  src/app/_components/Pagination.tsx
  src/app/_components/PostCard/DetailPostCard.tsx
  src/app/_components/PostCard/PostCardV.1.tsx
  src/app/_components/PostCard/PostCardV2.tsx
  src/app/_components/Table.tsx
  src/app/_components/Toast/Toast.tsx
  src/app/_components/Toast/ToastContainer.tsx
  src/app/_config/tableConfig.tsx
  src/app/_constants/locationData.ts
  src/app/_context/AppContext.tsx
  src/app/_context/AuthContext.tsx
  src/app/_context/NoticeContext.tsx
  src/app/_context/util/authEncryption.ts
  src/app/_context/util/recentNotices.ts
  src/app/_hooks/useAlbaTimeFormat.ts
  src/app/_hooks/useAuth.ts
  src/app/_hooks/useCreateImgUrl.ts
  src/app/_hooks/useFilteredNotices.ts
  src/app/_hooks/useGeolocation.ts
  src/app/_hooks/useImageCompressor.ts
  src/app/_hooks/useMouseDrag.ts
  src/app/_types/alarm.d.ts
  src/app/_types/announce.d.ts
  src/app/_types/auth.d.ts
  src/app/_types/owner.d.ts
  src/app/_types/worker.d.ts
  src/app/announce/_components/AllNotices.tsx
  src/app/announce/_components/EditAnnounce.tsx
  src/app/announce/_components/PostAnnounce.tsx
  src/app/announce/_components/UserNotice.tsx
  src/app/announce/detail/[id]/page.tsx
  src/app/announce/edit/page.tsx
  src/app/announce/post/page.tsx
  src/app/login/page.tsx
  src/app/search/components/SearchPage.tsx
  src/app/search/page.tsx
  src/app/signup/page.tsx
  src/app/store/detail/page.tsx
  tsconfig.json
Labels: 긴급, 버그

#173 버튼 배치 수정
  package-lock.json
  src/app/_components/PostCard/DetailPostCard.tsx
Labels: 긴급, 버그

#174 배포를 위한 main 브렌치 업데이트 - 2
  package-lock.json
  src/app/_components/PostCard/DetailPostCard.tsx
Labels: 업데이트

#175 가격표시 에러수정
  src/app/_components/PostCard/PostCard.tsx
Labels: 버그

#177 프로필이동, 프로필예외처리
  src/app/_components/Header/Header.tsx
  src/app/_components/PostCard/DetailPostCard.tsx
  src/app/announce/detail/[id]/page.tsx
  src/app/login/page.tsx
  src/app/profile/post/[id]/page.tsx
Labels: 긴급, 버그

#178 배포를 위한 main 브렌치 업데이트 - 3
  src/app/_components/Header/Header.tsx
  src/app/_components/PostCard/DetailPostCard.tsx
  src/app/announce/detail/[id]/page.tsx
  src/app/login/page.tsx
  src/app/profile/post/[id]/page.tsx
Labels: 업데이트

#180 Feature/#179 콘솔제거작업
  public/image/favicon.svg
  src/app/_api/imageURL_api.ts
  src/app/_components/Header/Header.tsx
  src/app/_components/PostCard/DetailPostCard.tsx
  src/app/_components/Table.tsx
  src/app/_context/AppContext.tsx
  src/app/_context/ApplicationContext.tsx
  src/app/_context/AuthContext.tsx
  src/app/_hooks/useImageCompressor.ts
  src/app/announce/_components/EditAnnounce.tsx
  src/app/announce/_components/PostAnnounce.tsx
  src/app/announce/detail/[id]/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/profile/page.tsx
  src/app/profile/post/[id]/page.tsx
  src/app/search/components/SearchPage.tsx
  src/app/store/detail/page.tsx
  src/app/store/post/page.tsx
Labels: 긴급, 버그, 업데이트

#181 배포를 위한 main 브렌치 업데이트 - 4
  public/image/favicon.svg
  src/app/_api/imageURL_api.ts
  src/app/_components/Header/Header.tsx
  src/app/_components/PostCard/DetailPostCard.tsx
  src/app/_components/Table.tsx
  src/app/_context/AppContext.tsx
  src/app/_context/ApplicationContext.tsx
  src/app/_context/AuthContext.tsx
  src/app/_hooks/useImageCompressor.ts
  src/app/announce/_components/EditAnnounce.tsx
  src/app/announce/_components/PostAnnounce.tsx
  src/app/announce/detail/[id]/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/profile/page.tsx
  src/app/profile/post/[id]/page.tsx
  src/app/search/components/SearchPage.tsx
  src/app/store/detail/page.tsx
  src/app/store/post/page.tsx
Labels: 업데이트

#182 Main배포를 위한 main 브렌치 업데이트 - 5
  src/app/_components/PostCard/DetailPostCard.tsx
Labels: 업데이트

#184 지난공고 누락버그 수정
  src/app/_components/PostCard/DetailPostCard.tsx
  src/app/_components/PostCard/PostCard.tsx
  src/app/_components/PostCard/PostCardV.1.tsx
  src/app/_components/PostCard/PostCardV2.tsx
Labels: 긴급, 버그

#185 배포를 위한 main 브렌치 업데이트 - 6
  src/app/_components/PostCard/DetailPostCard.tsx
  src/app/_components/PostCard/PostCard.tsx
  src/app/_components/PostCard/PostCardV.1.tsx
  src/app/_components/PostCard/PostCardV2.tsx
Labels: 업데이트

#186 Delete .github/workflows/sync.yml
  .github/workflows/sync.yml
Labels: 버그

#189 토큰 누락 수정
  src/app/_context/AuthContext.tsx
Labels: 긴급, 버그

#190 배포를 위한 main 브렌치 업데이트 - 7
  README.md
  src/app/_context/AuthContext.tsx
Labels: 업데이트
